# .github/workflows/ci.yml

name: Test & Coverage

# Gatilho: Este workflow roda sempre que um Pull Request for aberto ou atualizado
# para a branch 'main'.
on:
  pull_request:
    branches: [ main ]

jobs:
  # Nome do job
  test-and-report-coverage:
    # Máquina virtual que será usada para rodar o job
    runs-on: ubuntu-latest
    permissions:
      checks: write 
      pull-requests: write
      contents: read

    steps:
      # 1. Checkout do código
      # Baixa o código do repositório para a máquina virtual do Actions
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar o ambiente Node.js
      # Instala a versão do Node.js especificada e configura o cache do npm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      # 3. Instalar as dependências do projeto
      # Roda 'npm install' para baixar todos os pacotes. O 'ci' é otimizado para ambientes de CI.
      - name: Install dependencies
        run: npm ci

      # 4. Rodar os testes com cobertura
      # O '--' é usado para passar o argumento '--coverage' diretamente para o comando 'jest'
      # O Jest irá gerar uma pasta 'coverage' com os resultados
      - name: Run Jest tests with coverage
        run: npm test